In [2]:
import numpy as np

In [3]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [4]:
print(arr[1::3])

[10 25 40]


In [5]:
print(arr[-4:])  

[35 40 45 50]


In [6]:
arr[::2] = -1
print(arr) 

[-1 10 -1 20 -1 30 -1 40 -1 50]


In [7]:
fancy = arr[[2, 4, 6, 8]]
print(fancy) 

[-1 -1 -1 -1]
