# 1.) What is Vectorization?

Imagine you are a teacher.

You have marks of 10,000 students.

You want to add 5 bonus marks to every student.

There are two ways:

Method 1 (Python List)

Go student by student.

Student 1 → +5
Student 2 → +5
Student 3 → +5
...
Student 10000 → +5

This means Python has to repeat the same work again and again.

----------------------------

Method 2 (NumPy)

Tell NumPy only once:

"Add 5 to everyone."

NumPy performs the operation on the entire array at once.

This idea is called Vectorization.

-------------------

Definition:
Vectorization means performing an operation on an entire NumPy array at once without writing explicit Python loops.

---------------------

# Why does Vectorization exist?

Suppose we have

 - 1 million numbers

If Python processes them one by one, it becomes slower.

- NumPy was created for scientific computing.

- Instead of asking Python to repeat millions of operations,

- NumPy lets optimized C code do the work internally. This is one reason NumPy is much faster for numerical computations.

# Who predefined Vectorization?

You never write a function called vectorization().

 - It is not a function.

 - It is a feature of the NumPy library.

The developers of NumPy designed its array operations so that expressions like:

 - array + 5

or

 - array * 2

automatically work on every element.

------------------------

# Why is Vectorization Important in Data Science?

Imagine a hospital dataset.

 - 1,000,000 patients

Each patient's age is stored.

 - You need to increase every age by 1.

Without vectorization

 - for patient in dataset:

Very slow.

With NumPy

 - ages = ages + 1

Finished in one vectorized operation.

Machine Learning datasets often contain

 - 50,000 rows
 - 100,000 rows
 - 1 million rows
 - 10 million rows

Vectorization makes these operations practical.

----------------------------------

# Element-wise Operations

This is the first type of vectorization.

"Element-wise" means: The operation happens independently on each element at the same position.

In [2]:
# Example:

import numpy as np

arr = np.array([2,4,6,8])
print(arr)

print(arr*3)

[2 4 6 8]
[ 6 12 18 24]


Note from above example:
- It did NOT multiply the whole array together.

- It multiplied each individual element.

- That is why it is called element-wise multiplication.

------------

# Scalar Operations

A scalar is simply one single number.

Examples

- 5

- 100

- -3

- 2.5

All are scalars.

Scalar Operation means: Performing a mathematical operation between an array and one single value (scalar).

In [ ]:
# Example 1:

import numpy as np 

arr = np.array([1,2,3,4])

print(arr+10)

# Here , 10 is scalar

[11 12 13 14]


In [ ]:
# Example 2:

arr = np.array([4,5,6])
print(arr * 3)

# Here, 3 is the scalar

[12 15 18]


-----------

# Array vs Array Operations

Now instead of one scalar,

both sides are arrays.

In [ ]:
# Example 1:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1+arr2)

# NumPy matches positions.

[ 6  8 10 12]


It is an array-to-array operation.

------------

# Array Indexing

Array indexing means: Accessing a specific element from an array using its index (position).

# Why does indexing exist?

Suppose we have marks of 1 million students.

- marks = np.array([...])

Do we always need all 1 million values?

- No.

Sometimes we only need:

- The first student's mark.
- The last student's mark.
- The 10th student's mark.

Instead of reading the whole array, NumPy lets you directly access the value you want.

# Rule 1: NumPy Uses Zero-Based Indexing

 - This is exactly like Python lists.

 - It starts counting from 0, not 1.

In [7]:
# Example 1 (Indexing a 1D Array):

import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr[0])

print(arr[2])

1
3
