1. Introduction to NumPy (Day One):

NumPy is a Python library mainly used for:

- Fast calculations
- Working with arrays
- Data Science
- Machine Learning
- AI
- Data Analysis

Its Like a “A super powerful version of Python lists.”

2. Why NumPy is used in Data Science?

In Data Science we work with:

 - Huge datasets
 - Numbers  
 - Tables
 - Images
 - Machine Learning data

Normal Python lists become slow when data becomes huge.

NumPy solves this problem.

3. Python List vs NumPy Array

In [1]:
# Python List

numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]


In [3]:
# NumPy Array:

import numpy as np

numbers = np.array([1,2,3,4,5])
print(numbers)

[1 2 3 4 5]


4. Why NumPy is Faster?

 - Python list stores different types together:

   [1, "hello", True, 5.5]

 - But NumPy arrays usually store same type data only:

   [1, 2, 3, 4]

Because of this:

 - memory becomes efficient
 - calculations become faster
 - Data Science operations become easier

In [ ]:
# Quick Practice:

# Q1.) Create a normal Python list with: 10 20 30

numbers = [10,20,30]
print(numbers)

[10, 20, 30]


In [5]:
type(numbers)

list

In [6]:
# Q2.) Create a NumPy array with: 5, 10, 15

import numpy as np 

numbers = np.array([5,10,15])
print(numbers)

[ 5 10 15]


In [7]:
type(numbers)

numpy.ndarray

5. Importing NumPy

In [9]:
# Before using NumPy, we must import it.

# Basic Syntax:
import numpy as np

Understanding Every Word:

a.) Import

 - import means “Bring this library into my program.”

 - Python itself does not automatically load NumPy.

 - So we import it first.

b.) numpy

 - This is the actual library name (numpy).

c.) as

as means “Give another shorter nickname.”

d.) np

    This is the nickname (alias).

    Instead of writing:

    - numpy.array()

    we write:

    - np.array()


 - Much shorter and easier.
 - Almost every Data Scientist uses:

import numpy as np

So this is the standard style.

---------------------------------------------------------------------------------------

6. ndarray

 - Very important term.

When we create a NumPy array:

 - np.array([1,2,3])

the object type becomes:

 - numpy.ndarray

-------------------------------------------------------------------------------------------------------------

7. What does ndarray mean?

n-dimensional array

Meaning:
 - 1D array
 - 2D array
 - 3D array
 - and so on

All are called:
 - ndarray

In [10]:
# Checking the Type:

import numpy as np

arr = np.array({2,4,6,8})

print(type(arr))

<class 'numpy.ndarray'>


8. Understanding Array Dimensions

This is one of the MOST important NumPy concepts.

In Data Science:

 - tables
 - images
 - datasets
 - machine learning inputs
 
all use dimensions.

Dimension, simply means “How data is organized.”

------------------------------------------------------

1D Array:

 - Its Like a Straight Line of Values.

In [11]:
# Simple Example:

import numpy as np

numbers = [3,6,9,12,15]
arr = np.array(numbers)

print(arr)

[ 3  6  9 12 15]


In [12]:
print(type(arr))

<class 'numpy.ndarray'>


Understanding .ndim

ndim means "number of dimensions".

In [14]:
# Checking dimension using ndim:

print(f"Number of Dimension : {arr.ndim}")

Number of Dimension : 1


2D Array

2D means:
 - rows + columns
 - Like a table.

In [15]:
# Simple Example:

numbers = ([1,2,3,4,5],[6,7,8,9,10])

arr2 = np.array(numbers)

print(numbers)

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])


In [16]:
print(arr2.ndim)

2


Real-Life Analogy

 - 2D array is like a Excel sheet / table
 - Rows and columns both exist.

In [17]:
# Checking Shape of Array (Very Important):

print(arr2.shape)

(2, 5)


Here, In Above Cell:

    2 ---> represents number of rows.
    3 ---> represents number of columns.

3D Array

- 3D arrays are arrays inside arrays inside arrays.