In [18]:
# Questions:

# ## Section A: NumPy Basics

# ### Q1.
# Write a program to import the NumPy library using the standard alias.

# ### Q2.
# Write a program to create a normal Python list containing:
# - 10, 20, 30, 40, 50

# Then print:
# - The list
# - The data type of the list

# ### Q3.
# Write a program to create a NumPy array containing:
# - 10, 20, 30, 40, 50

# Then print:
# - The array
# - The data type of the array

# ### Q4.
# Write a program to create a NumPy array containing the prices:
# - 150, 220, 80, 500, 350

# Print the array.

# ### Q5.
# Write a program to create the following NumPy array:
# - [5, 10, 15, 20, 25]

# Then print:
# - The array
# - The type of the array
# - Number of dimensions (`ndim`)
# - Shape of the array

# ---

# # Section B: Array Dimensions

# ### Q6.
# Write a program to create the following 1D array:
# - [1, 2, 3, 4, 5]

# Then print:
# - Array
# - Shape
# - Number of dimensions

# ### Q7.
# Write a program to create the following 2D array:

# [[10,20],
#  [30,40]]

# Then print:
# - Array
# - Shape
# - Number of dimensions

# ### Q8.
# Write a program to create the following 2D array:

# [[5,10,15],
#  [20,25,30]]

# Then print:
# - Shape
# - Number of dimensions

# ### Q9.
# Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]]
# ]

# Then print:
# - Shape
# - Number of dimensions

# ### Q10.
# Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]],

#  [[5,6],
#   [7,8]]
# ]

# Then print:
# - Shape
# - Number of dimensions

# ---

# # Section C: np.arange()

# ### Q11.
# Write a program to create numbers from 0 to 9 using `np.arange()`.

# ### Q12.
# Write a program to create numbers from 1 to 20 using `np.arange()`.

# ### Q13.
# Write a program to create all even numbers between 2 and 20 using `np.arange()`.

# ### Q14.
# Write a program to create all odd numbers between 1 and 19 using `np.arange()`.

# ### Q15.
# Write a program to create numbers from 50 to 100 with a step size of 10 using `np.arange()`.

# ---

# # Section D: np.linspace()

# ### Q16.
# Write a program to generate 5 equally spaced numbers between 1 and 10.

# ### Q17.
# Write a program to generate 8 equally spaced numbers between 0 and 100.

# ### Q18.
# Write a program to generate 6 equally spaced numbers between 10 and 60 without including the endpoint.

# ### Q19.
# Write a program to generate 11 equally spaced numbers between 0 and 1.

# ### Q20.
# Write a program to generate 4 equally spaced numbers between 20 and 40.

# ---

# # Section E: np.zeros() and np.ones()

# ### Q21.
# Write a program to create an array containing 8 zeros.

# ### Q22.
# Write a program to create a 2 × 4 array filled with zeros.

# ### Q23.
# Write a program to create an array containing 10 ones.

# ### Q24.
# Write a program to create a 3 × 2 array filled with ones.

# ### Q25.
# Write a program to create a 4 × 3 zeros array and print:
# - The array
# - The shape

# ---

# # Section F: Random Arrays

# ### Q26.
# Write a program to generate 10 random integers between 1 and 50.

# ### Q27.
# Write a program to generate 6 random integers between 100 and 200 using keyword arguments (`low`, `high`, `size`).

# ### Q28.
# Write a program to generate a 2 × 3 random integer array containing numbers between 10 and 99.

# ### Q29.
# Write a program to generate 5 random decimal numbers using `np.random.rand()`.

# ### Q30.
# Write a program to generate a 3 × 3 random decimal array using `np.random.rand()`.

# ---

# # Section G: np.empty()

# ### Q31.
# Write a program to create an empty array containing 5 elements.

# ### Q32.
# Write a program to create an empty integer array containing 8 elements.

# ---

# # Section H: Mixed Practice

# ### Q33.
# Write a program to create:
# - One 1D array
# - One 2D array
# - One 3D array

# Then print:
# - The arrays
# - Their shapes
# - Their number of dimensions

# ### Q34.
# Write a program to create:
# - A zeros array
# - A ones array
# - A random integer array

# Then print all three arrays.

# ### Q35. (Challenge)

# Write a program to create:
# - A 3 × 3 zeros array
# - A 3 × 3 ones array
# - A 3 × 3 random integer array containing numbers between 1 and 20
# - A 3 × 3 random decimal array

# Finally, print all four arrays in a neat and readable format.

# Numpy Practice Questions - Day One

# Section A: NumPy Basics

In [19]:
# 1.) Write a program to import the NumPy library using the standard alias.

import numpy as np


In [20]:

# 2.) Write a program to create a normal Python list containing:
# - 10, 20, 30, 40, 50
# Then print:
# - The list
# - The data type of the list

l1 = [10, 20, 30, 40, 50]

print(l1)

print(type(l1))

[10, 20, 30, 40, 50]
<class 'list'>


In [21]:
# 4.) Write a program to create a NumPy array containing:
# 10, 20, 30, 40, 50

# Then print:
# - The array
# - The data type of the array

import numpy as np

a1 = [10,20,30,40,50]

arr = np.array(a1)
print(arr)

# Checking its type:

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [22]:
# 4.) Write a program to create a NumPy array containing the prices:
# 150, 220, 80, 500, 350
# Print the array.

import numpy as np

arr = np.array([150, 220, 80, 500, 350])
print(arr)

[150 220  80 500 350]


In [23]:
# 5.) Write a program to create the following NumPy array:
# - [5, 10, 15, 20, 25]

# Then print:
# - The array
# - The type of the array
# - Number of dimensions 
# - Shape of the array

In [24]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])
print(arr)

print(type(arr))

print(f"Number of Dimensions : {arr.ndim}")

print(f"Shape of the array : {arr.shape}")


[ 5 10 15 20 25]
<class 'numpy.ndarray'>
Number of Dimensions : 1
Shape of the array : (5,)


# Section B: Array Dimensions

In [25]:
# 6.) Write a program to create the following 1D array:
#  [1, 2, 3, 4, 5]
# Then print:
# - Array
# - Shape
# - Number of dimensions

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of Dimensions : {arr.ndim}")


[1 2 3 4 5]
Shape of the Array : (5,)
Number of Dimensions : 1


In [26]:
# 7.) Write a program to create the following 2D array:

# [[10,20],
#  [30,40]]

# Then print:
# - Array
# - Shape
# - Number of dimensions

arr = np.array([[10,20],[30,40]])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of dimensions : {arr.ndim}")

[[10 20]
 [30 40]]
Shape of the Array : (2, 2)
Number of dimensions : 2


In [27]:
# 8.) Write a program to create the following 2D array:

# [[5,10,15],
#  [20,25,30]]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[5,10,15],[20,25,30]])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of Dimension : {arr.ndim}")

[[ 5 10 15]
 [20 25 30]]
Shape of the Array : (2, 3)
Number of Dimension : 2


In [28]:
# 9.) Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]]
# ]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[[1,2],[3,4]]])

print(arr)

print(f"Shape of Array : {arr.shape}")
print(f"Number of Dimensions : {arr.ndim}")


[[[1 2]
  [3 4]]]
Shape of Array : (1, 2, 2)
Number of Dimensions : 3


In [29]:
# 10.) Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]],

#  [[5,6],
#   [7,8]]
# ]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr.shape)

print(arr.ndim)

(2, 2, 2)
3
