# 1. Introduction to NumPy (Day One):

NumPy is a Python library mainly used for:

- Fast calculations
- Working with arrays
- Data Science
- Machine Learning
- AI
- Data Analysis

Its Like a “A super powerful version of Python lists.”

# 2. Why NumPy is used in Data Science?

In Data Science we work with:

 - Huge datasets
 - Numbers  
 - Tables
 - Images
 - Machine Learning data

Normal Python lists become slow when data becomes huge.

NumPy solves this problem.

# 3. Python List vs NumPy Array

In [1]:
# Python List

numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]


In [2]:
# NumPy Array:

import numpy as np

numbers = np.array([1,2,3,4,5])
print(numbers)

[1 2 3 4 5]


# 4. Why NumPy is Faster?

 - Python list stores different types together:

   [1, "hello", True, 5.5]

 - But NumPy arrays usually store same type data only:

   [1, 2, 3, 4]

Because of this:

 - memory becomes efficient
 - calculations become faster
 - Data Science operations become easier

In [3]:
# Quick Practice:

# Q1.) Create a normal Python list with: 10 20 30

numbers = [10,20,30]
print(numbers)

[10, 20, 30]


In [4]:
type(numbers)

list

In [5]:
# Q2.) Create a NumPy array with: 5, 10, 15

import numpy as np 

numbers = np.array([5,10,15])
print(numbers)

[ 5 10 15]


In [6]:
type(numbers)

numpy.ndarray

# 5. Importing NumPy

In [7]:
# Before using NumPy, we must import it.

# Basic Syntax:
import numpy as np

Understanding Every Word:

a.) Import

 - import means “Bring this library into my program.”

 - Python itself does not automatically load NumPy.

 - So we import it first.

b.) numpy

 - This is the actual library name (numpy).

c.) as

as means “Give another shorter nickname.”

d.) np

    This is the nickname (alias).

    Instead of writing:

    - numpy.array()

    we write:

    - np.array()


 - Much shorter and easier.
 - Almost every Data Scientist uses:

import numpy as np

So this is the standard style.

---------------------------------------------------------------------------------------

# 6. ndarray

 - Very important term.

When we create a NumPy array:

 - np.array([1,2,3])

the object type becomes:

 - numpy.ndarray

-------------------------------------------------------------------------------------------------------------

# 7. What does ndarray mean?

n-dimensional array

Meaning:
 - 1D array
 - 2D array
 - 3D array
 - and so on

All are called:
 - ndarray

In [8]:
# Checking the Type:

import numpy as np

arr = np.array({2,4,6,8})

print(type(arr))

<class 'numpy.ndarray'>


# 8. Understanding Array Dimensions

This is one of the MOST important NumPy concepts.

In Data Science:

 - tables
 - images
 - datasets
 - machine learning inputs
 
all use dimensions.

Dimension, simply means “How data is organized.”

------------------------------------------------------

1D Array:

 - Its Like a Straight Line of Values.

In [9]:
# Simple Example:

import numpy as np

numbers = [3,6,9,12,15]
arr = np.array(numbers)

print(arr)

[ 3  6  9 12 15]


In [10]:
print(type(arr))

<class 'numpy.ndarray'>


Understanding .ndim

ndim means "number of dimensions".

In [11]:
# Checking dimension using ndim:

print(f"Number of Dimension : {arr.ndim}")

Number of Dimension : 1


2D Array

2D means:
 - rows + columns
 - Like a table.

In [12]:
# Simple Example:

numbers = ([1,2,3,4,5],[6,7,8,9,10])

arr2 = np.array(numbers)

print(numbers)

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])


In [13]:
print(arr2.ndim)

2


Real-Life Analogy

 - 2D array is like a Excel sheet / table
 - Rows and columns both exist.

In [14]:
# Checking Shape of Array (Very Important):

print(arr2.shape)

(2, 5)


Here, In Above Cell:

    2 ---> represents number of rows.
    3 ---> represents number of columns.

3D Array

- 3D arrays are arrays inside arrays inside arrays.

In [15]:
# Simple Example:

numbers =  [[[1,2,3],[4,5,6]]]

arr3 = np.array(numbers)
print(arr3)


[[[1 2 3]
  [4 5 6]]]


In [16]:
print(arr3.ndim)

3


In [17]:
arr3.shape

(1, 2, 3)

Note to remember : More square brackets = more dimensions

---------------------------------------------

# 9. Creating Arrays

 - Now we learn the MOST used NumPy functions in Data Science.

 - These functions help us quickly generate arrays

A.) np.array()

- We already used this above.

- Used to convert Python lists into NumPy arrays.

In [18]:
# Example:

import numpy as np


nums = ([1,2,3,4,5,6])

arr = np.array(nums)

print(arr)


[1 2 3 4 5 6]


In [19]:
print(type(arr))

<class 'numpy.ndarray'>


-------------------------------

B.) np.arange()

 - Very important.
 - Works like Python range().

Syntax:
 - np.arange(start, stop, step)

In [46]:
# Example 1:

import numpy as np

arr = np.arange(1,11,1)

print(arr)
print(type(arr))
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1


here,

 - start = 1
 - stop = 11
 - step = 1

In [21]:
print(arr.shape)

(10,)


In [22]:
# Example 2:

arr = np.arange(2,21,2)

print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [23]:
print(type(arr))

<class 'numpy.ndarray'>


In [24]:
arr.ndim

1

arange() = Counting numbers with a pattern.

------------------------------------------------------------------------------------------------------

C.) np.linspace()

 - Very important in Data Science and graphs.
 - Creates evenly spaced numbers.

Syntax:

 - np.linspace(start, stop, how_many_numbers)

In [25]:
arr = np.linspace(1,10,5 , endpoint=False)
print(arr)

[1.  2.8 4.6 6.4 8.2]


Understanding Properly:

np.linspace(1,10,5) means:

 - “Give me 5 equally spaced numbers between 1 and 10.”

--------------------------------------------------

Understanding how "Endpoint" is used:
 - np.linspace(start, stop, total_numbers, endpoint=False)
  means:
 - start from 1
 - go toward 10
 - create 5 numbers
 - but DO NOT include 10

--------------------------

D.) np.zeros()

- This function creates arrays filled with zeros.

In [26]:
# Example 1:

np_zeros = np.zeros(10)
print(np_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


NumPy defaults to float sometimes. So, inorder to change it we must use "dtype = ".

In [27]:
# Example 2 (making 2D array with zeros and also using dtype):

arr_2d = np.zeros((3,4),dtype=int)
print(arr_2d)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [28]:
# Here:
    # 3 represents number of rows.
    # 4 represents number of columns.

--------------------------------------------------------------------------------------------------

E.) np.ones()

 - This Function creates an array filled with ones (1).

In [29]:
# Example 1:

arr = np.ones(5,dtype=int)
print(arr)

[1 1 1 1 1]


In [30]:
# Example 2 (making 3D array filled with ones)

arr = np.ones((3,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


----------------------------------------

F.) np.random.randint():

- NumPy can also create arrays with random numbers using its random module. For example, we can use randint() to generate a random integer within a  range.
- This Function Simply, Generates Random Integers.

Important Note:
 - Output changes every run because numbers are random.

In [31]:
# Example 1:

arr = np.random.randint(1,10,5)
print(arr)

[5 5 6 8 8]


Understanding:
    
np.random.randint(1,10,5) means:
- start = 1
- stop = 10
- total_numbers = 5

-----------------------------------------

G. np.random.rand():

This Function generates random decimal numbers between:
 - 0 and 1

In [32]:
import numpy as np

arr = np.random.rand(3)
print(arr)

[0.54478261 0.39055735 0.80464355]


In [33]:
# Creating a 2D Random Array:

arr = np.random.rand(2,3)
print(arr)

[[0.90035559 0.76060945 0.92209722]
 [0.25781611 0.80664655 0.27580142]]


In [34]:
print(f"Number of Dimension: {arr.ndim}")

Number of Dimension: 2


In [35]:
arr.shape

(2, 3)

----------

H.) np.empty():

 - This Function creates an empty array.
 

In [43]:
# Example 1:

arr = np.empty(10, dtype=int)
print(arr)

[          0  1072693248  1717986918  1074161254  1717986918  1074947686
 -1717986918  1075419545  1717986918  1075865190]


In [44]:
print(arr.shape)

(10,)


In [45]:
print(arr.ndim)

1
