In [18]:
# Questions:

# ## Section A: NumPy Basics

# ### Q1.
# Write a program to import the NumPy library using the standard alias.

# ### Q2.
# Write a program to create a normal Python list containing:
# - 10, 20, 30, 40, 50

# Then print:
# - The list
# - The data type of the list

# ### Q3.
# Write a program to create a NumPy array containing:
# - 10, 20, 30, 40, 50

# Then print:
# - The array
# - The data type of the array

# ### Q4.
# Write a program to create a NumPy array containing the prices:
# - 150, 220, 80, 500, 350

# Print the array.

# ### Q5.
# Write a program to create the following NumPy array:
# - [5, 10, 15, 20, 25]

# Then print:
# - The array
# - The type of the array
# - Number of dimensions (`ndim`)
# - Shape of the array

# ---

# # Section B: Array Dimensions

# ### Q6.
# Write a program to create the following 1D array:
# - [1, 2, 3, 4, 5]

# Then print:
# - Array
# - Shape
# - Number of dimensions

# ### Q7.
# Write a program to create the following 2D array:

# [[10,20],
#  [30,40]]

# Then print:
# - Array
# - Shape
# - Number of dimensions

# ### Q8.
# Write a program to create the following 2D array:

# [[5,10,15],
#  [20,25,30]]

# Then print:
# - Shape
# - Number of dimensions

# ### Q9.
# Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]]
# ]

# Then print:
# - Shape
# - Number of dimensions

# ### Q10.
# Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]],

#  [[5,6],
#   [7,8]]
# ]

# Then print:
# - Shape
# - Number of dimensions

# ---

# # Section C: np.arange()

# ### Q11.
# Write a program to create numbers from 0 to 9 using `np.arange()`.

# ### Q12.
# Write a program to create numbers from 1 to 20 using `np.arange()`.

# ### Q13.
# Write a program to create all even numbers between 2 and 20 using `np.arange()`.

# ### Q14.
# Write a program to create all odd numbers between 1 and 19 using `np.arange()`.

# ### Q15.
# Write a program to create numbers from 50 to 100 with a step size of 10 using `np.arange()`.

# ---

# # Section D: np.linspace()

# ### Q16.
# Write a program to generate 5 equally spaced numbers between 1 and 10.

# ### Q17.
# Write a program to generate 8 equally spaced numbers between 0 and 100.

# ### Q18.
# Write a program to generate 6 equally spaced numbers between 10 and 60 without including the endpoint.

# ### Q19.
# Write a program to generate 11 equally spaced numbers between 0 and 1.

# ### Q20.
# Write a program to generate 4 equally spaced numbers between 20 and 40.

# ---

# # Section E: np.zeros() and np.ones()

# ### Q21.
# Write a program to create an array containing 8 zeros.

# ### Q22.
# Write a program to create a 2 × 4 array filled with zeros.

# ### Q23.
# Write a program to create an array containing 10 ones.

# ### Q24.
# Write a program to create a 3 × 2 array filled with ones.

# ### Q25.
# Write a program to create a 4 × 3 zeros array and print:
# - The array
# - The shape

# ---

# # Section F: Random Arrays

# ### Q26.
# Write a program to generate 10 random integers between 1 and 50.

# ### Q27.
# Write a program to generate 6 random integers between 100 and 200 using keyword arguments (`low`, `high`, `size`).

# ### Q28.
# Write a program to generate a 2 × 3 random integer array containing numbers between 10 and 99.

# ### Q29.
# Write a program to generate 5 random decimal numbers using `np.random.rand()`.

# ### Q30.
# Write a program to generate a 3 × 3 random decimal array using `np.random.rand()`.

# ---

# # Section G: np.empty()

# ### Q31.
# Write a program to create an empty array containing 5 elements.

# ### Q32.
# Write a program to create an empty integer array containing 8 elements.

# ---

# # Section H: Mixed Practice

# ### Q33.
# Write a program to create:
# - One 1D array
# - One 2D array
# - One 3D array

# Then print:
# - The arrays
# - Their shapes
# - Their number of dimensions

# ### Q34.
# Write a program to create:
# - A zeros array
# - A ones array
# - A random integer array

# Then print all three arrays.

# ### Q35. (Challenge)

# Write a program to create:
# - A 3 × 3 zeros array
# - A 3 × 3 ones array
# - A 3 × 3 random integer array containing numbers between 1 and 20
# - A 3 × 3 random decimal array

# Finally, print all four arrays in a neat and readable format.

# Numpy Practice Questions - Day One

# Section A: NumPy Basics

In [19]:
# 1.) Write a program to import the NumPy library using the standard alias.

import numpy as np


In [20]:

# 2.) Write a program to create a normal Python list containing:
# - 10, 20, 30, 40, 50
# Then print:
# - The list
# - The data type of the list

l1 = [10, 20, 30, 40, 50]

print(l1)

print(type(l1))

[10, 20, 30, 40, 50]
<class 'list'>


In [21]:
# 4.) Write a program to create a NumPy array containing:
# 10, 20, 30, 40, 50

# Then print:
# - The array
# - The data type of the array

import numpy as np

a1 = [10,20,30,40,50]

arr = np.array(a1)
print(arr)

# Checking its type:

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [22]:
# 4.) Write a program to create a NumPy array containing the prices:
# 150, 220, 80, 500, 350
# Print the array.

import numpy as np

arr = np.array([150, 220, 80, 500, 350])
print(arr)

[150 220  80 500 350]


In [23]:
# 5.) Write a program to create the following NumPy array:
# - [5, 10, 15, 20, 25]

# Then print:
# - The array
# - The type of the array
# - Number of dimensions 
# - Shape of the array

In [24]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])
print(arr)

print(type(arr))

print(f"Number of Dimensions : {arr.ndim}")

print(f"Shape of the array : {arr.shape}")


[ 5 10 15 20 25]
<class 'numpy.ndarray'>
Number of Dimensions : 1
Shape of the array : (5,)


# Section B: Array Dimensions

In [25]:
# 6.) Write a program to create the following 1D array:
#  [1, 2, 3, 4, 5]
# Then print:
# - Array
# - Shape
# - Number of dimensions

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of Dimensions : {arr.ndim}")


[1 2 3 4 5]
Shape of the Array : (5,)
Number of Dimensions : 1


In [26]:
# 7.) Write a program to create the following 2D array:

# [[10,20],
#  [30,40]]

# Then print:
# - Array
# - Shape
# - Number of dimensions

arr = np.array([[10,20],[30,40]])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of dimensions : {arr.ndim}")

[[10 20]
 [30 40]]
Shape of the Array : (2, 2)
Number of dimensions : 2


In [27]:
# 8.) Write a program to create the following 2D array:

# [[5,10,15],
#  [20,25,30]]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[5,10,15],[20,25,30]])

print(arr)

print(f"Shape of the Array : {arr.shape}")

print(f"Number of Dimension : {arr.ndim}")

[[ 5 10 15]
 [20 25 30]]
Shape of the Array : (2, 3)
Number of Dimension : 2


In [28]:
# 9.) Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]]
# ]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[[1,2],[3,4]]])

print(arr)

print(f"Shape of Array : {arr.shape}")
print(f"Number of Dimensions : {arr.ndim}")


[[[1 2]
  [3 4]]]
Shape of Array : (1, 2, 2)
Number of Dimensions : 3


In [29]:
# 10.) Write a program to create the following 3D array:

# [
#  [[1,2],
#   [3,4]],

#  [[5,6],
#   [7,8]]
# ]

# Then print:
# - Shape
# - Number of dimensions

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr.shape)

print(arr.ndim)

(2, 2, 2)
3


In [2]:
# 11.) Write a program to create numbers from 0 to 9 using `np.arange()`.

import numpy as np

arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 12.Write a program to create numbers from 1 to 20 using `np.arange()`.

import numpy as np

arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
# 13.)  Write a program to create all even numbers between 2 and 20 using `np.arange()`.

import numpy as np

arr = np.arange(2,21,2)
print(arr)
print(arr.shape)

[ 2  4  6  8 10 12 14 16 18 20]
(10,)


In [6]:
# 14.) Write a program to create all odd numbers between 1 and 19 using `np.arange()`.

import numpy as np

arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [7]:
# 15.) Write a program to create numbers from 50 to 100 with a step size of 10 using `np.arange()`.

import numpy as np 

arr = np.arange(50,100,10)
print(arr)


[50 60 70 80 90]


In [9]:
# 16.) Write a program to generate 5 equally spaced numbers between 1 and 10.

import numpy as np 

arr = np.linspace(1,10,5)
print(arr)


[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
# 17.) Write a program to generate 8 equally spaced numbers between 0 and 100.

import numpy as np

arr = np.linspace(0,100,8)
print(arr)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [11]:
# 18.) Write a program to generate 6 equally spaced numbers between 10 and 60 without including the endpoint.

import numpy as np

arr = np.linspace(10,60,6 ,endpoint=False)
print(arr)

[10.         18.33333333 26.66666667 35.         43.33333333 51.66666667]


In [12]:
# 19.) Write a program to generate 11 equally spaced numbers between 0 and 1.

import numpy as np

arr = np.linspace(0,1,11)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
# 20.) Write a program to generate 4 equally spaced numbers between 20 and 40.

import numpy as np

arr = np.linspace(20,40,4)
print(arr)


[20.         26.66666667 33.33333333 40.        ]


In [14]:

# 21.) Write a program to create an array containing 8 zeros.

import numpy as np

arr = np.zeros(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# 22.) Write a program to create a 2 × 4 array filled with zeros.

import numpy as np

arr = np.zeros((2,4))
print(arr)
print(arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 4)


In [20]:
# 23.) Write a program to create an array containing 10 ones.

import numpy as np

arr = np.ones(10, dtype=int)
print(arr)


[1 1 1 1 1 1 1 1 1 1]


In [22]:
# 24.) Write a program to create a 3 × 2 array filled with ones.

import numpy as np

arr = np.ones((3,2),dtype=int)
print(arr)


[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# Write a program to create a 4 × 3 zeros array and print:
# - The array
# - The shape

import numpy as np

arr = np.zeros((4,3), dtype=int)
print(arr)

print(arr.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)


In [26]:
# 26.) Write a program to generate 10 random integers between 1 and 50.

import numpy as np

arr = np.random.randint(1,50,10)

print(arr)

[32 34 37  5 26 45 46 36 22 42]


In [1]:
# 27.) Write a program to generate 6 random integers between 100 and 200 using keyword arguments (`low`, `high`, `size`).

import numpy as np

arr = np.random.randint(low=100,high=200,size=6)

print(arr)

[102 124 115 147 137 124]


In [2]:
# 28.) Write a program to generate a 2 × 3 random integer array containing numbers between 10 and 99.

import numpy as np

arr = np.random.randint(10,99,(2,3))
print(arr)

[[34 29 94]
 [52 93 50]]


In [3]:
# 29.) Write a program to generate 5 random decimal numbers using `np.random.rand()`.

import numpy as np

arr = np.random.rand(5)
print(arr)

[0.84964629 0.27840344 0.58219632 0.39193717 0.13962515]


In [5]:
# 30.) Write a program to generate a 3 × 3 random decimal array using `np.random.rand()`.

import numpy as np

arr = np.random.rand(3,3)
print(arr)

[[0.81413379 0.8418643  0.927246  ]
 [0.77390604 0.415912   0.08106258]
 [0.37639371 0.03195797 0.02556985]]


In [6]:
# 31.) Write a program to create an empty array containing 5 elements.

import numpy as np

arr = np.empty(5)
print(arr)

[0.84964629 0.27840344 0.58219632 0.39193717 0.13962515]


In [7]:
# 32.) Write a program to create an empty integer array containing 8 elements.

import numpy as np

arr = np.empty(8)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
# 33.) Write a program to create:
# - One 1D array
# - One 2D array
# - One 3D array

# Then print:
# - The arrays
# - Their shapes
# - Their number of dimensions

import numpy as np

arr1 = np.random.rand(4)
print(f"1D Array : {arr1}")
print(arr1.shape)
print(arr1.ndim)

arr2 = np.random.rand(2,3)
print(f"2D Array : {arr2} ")
print(arr2.shape)
print(arr2.ndim)

arr3 = np.random.rand(2,2,4)
print(f"3D Array : {arr3}")
print(arr3.shape)
print(arr3.ndim)



1D Array : [0.86078476 0.6679813  0.79148493 0.14306188]
(4,)
1
2D Array : [[0.51906946 0.01801393 0.47552398]
 [0.30214293 0.06703976 0.63907942]] 
(2, 3)
2
3D Array : [[[0.59796142 0.66077531 0.16064852 0.52338137]
  [0.9385978  0.20436504 0.74510727 0.67747708]]

 [[0.69539169 0.79009199 0.18731575 0.73003867]
  [0.5297553  0.28970652 0.0622956  0.13680207]]]
(2, 2, 4)
3


In [ ]:
# 34.) Write a program to create:
# - A zeros array
# - A ones array
# - A random integer array
# Then print all three arrays.

import numpy as np

arr0 = np.zeros((1,2,3))
print(arr0)

arr1 = np.ones((2,2,3))
print(arr1)

arr2 = np.random.randint(10,50,(3,2,3))
print(arr2)

[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[14 34 33]
  [11 19 17]]

 [[19 16 40]
  [33 49 26]]

 [[41 26 23]
  [10 49 28]]]


In [28]:
### Q35. (Challenge)

# Write a program to create:
# - A 3 × 3 zeros array
# - A 3 × 3 ones array
# - A 3 × 3 random integer array containing numbers between 1 and 20
# - A 3 × 3 random decimal array

# Finally, print all four arrays in a neat and readable format.

import numpy as np 

arr0 = np.zeros((3,3))
print(arr0)

arr1 = np.ones((3,3))
print(arr1)

arr2 = np.random.randint(1,20,(3,3))
print(arr2)

arr3 = np.random.rand(3,3)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[12 14  3]
 [ 4  5 18]
 [15  6 18]]
[[0.82026147 0.22147231 0.13141578]
 [0.34771399 0.04750195 0.71306852]
 [0.83733638 0.36093097 0.79404192]]
